FROM  golang:1.17.2-bullseye AS builder

WORKDIR /usr/local/app

COPY . .

RUN go mod download 

RUN cp -av envs/in.cluster.env ./.env

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o kubelog-go .

FROM alpine3

COPY --from=builder /usr/local/app/ /

CMD ["/kubelog-go"]